In [3]:
def my_fun():
    print("hello")

In [4]:
my_fun()

hello


In [12]:
def sum(a,b):
    c

In [13]:
a=3
b=4
c=a+b


In [14]:
c

7

In [15]:
a=[1,2,3,4,5]

In [17]:
a

[1, 2, 3, 4, 5]

In [18]:
text="hello world hi"

In [19]:
text.split()

['hello', 'world', 'hi']

In [20]:
t="hel,lo,wor,ld hi"

In [21]:
t.split(",")

['hel', 'lo', 'wor', 'ld hi']

In [22]:
ab=text.split()

In [23]:
ab[0]

'hello'

In [24]:
ab[-1]

'hi'

In [25]:
x=[1,2,3,4,5]
for i in x:
    print(i)

1
2
3
4
5


In [26]:
for i in range(0,10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [29]:
for i in range(10,0,-1):
    print(i)

10
9
8
7
6
5
4
3
2
1


In [30]:
list1=[]
te=int(input("enter the size of array"))
for i in range(0,te):
    l=input("enter the values:")
    list1.append(l)

enter the size of array5
enter the values:1
enter the values:2
enter the values:3
enter the values:4
enter the values:5


In [31]:
list1

['1', '2', '3', '4', '5']

In [32]:
import math
r=2
rs=math.pi*r*r

In [33]:
rs

12.566370614359172

In [1]:
from package import pack
pack.sum(4,5)

9


In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3,4])

In [4]:
a

array([1, 2, 3, 4])

In [5]:
z=np.zeros((2,3))

In [6]:
z

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
r=np.arange(0,10,2)

In [8]:
r

array([0, 2, 4, 6, 8])

In [11]:
b=np.array([4,5,6,7])

In [12]:
a+b

array([ 5,  7,  9, 11])

In [13]:
np.mean(a)

2.5

In [14]:
np.max(a)

4

In [15]:
c=np.array([[1,2],[3,4]])

In [16]:
c

array([[1, 2],
       [3, 4]])

In [17]:
d=np.array([[4,8],[6,9]])

In [18]:
c+d

array([[ 5, 10],
       [ 9, 13]])

In [22]:
c*d

array([[ 4, 16],
       [18, 36]])

In [23]:
f=np.dot(c,d)
f

array([[16, 26],
       [36, 60]])

In [24]:
f.T

array([[16, 36],
       [26, 60]])

In [25]:
print("\n matrix 1:\n",c)
print("\n matrix 1:\n",d)
print("\n Addition\n",c+d)
print("\n Substraction\n",c-d)
print("\n Multiplication(Element Wise)\n",c*d)
print("\n Dot Multiplication(row x column) \n",f)
print("\n Transpose\n",f.T)


 matrix 1:
 [[1 2]
 [3 4]]

 matrix 1:
 [[4 8]
 [6 9]]

 Addition
 [[ 5 10]
 [ 9 13]]

 Substraction
 [[-3 -6]
 [-3 -5]]

 Multiplication(Element Wise)
 [[ 4 16]
 [18 36]]

 Dot Multiplication(row x column) 
 [[16 26]
 [36 60]]

 Transpose
 [[16 36]
 [26 60]]
