In [1]:
import numpy as np 
from sklearn import datasets,metrics 
from sklearn.model_selection import train_test_split 
from sklearn.naive_bayes import GaussianNB 
from sklearn.metrics import accuracy_score

In [2]:
iris=datasets.load_iris() 
X=iris.data 
y=iris.target 
#split the data into training and testing sets(80% training,20% testing) 
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42) 

In [3]:
nb_classifier=GaussianNB()

In [4]:
nb_classifier.fit(X_train,y_train)

GaussianNB()

In [5]:
#make predictions on the testing data 
y_pred=nb_classifier.predict(X_test) 
#calculate the accuracy of the classifier 
accuracy=accuracy_score(y_test,y_pred) 
print(accuracy) 
print(f"Accuracy: {accuracy*100:.2f}%")

1.0
Accuracy: 100.00%


In [8]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Load the iris dataset
iris = datasets.load_iris()
X = iris.data
y = iris.target

# Split the data into training and testing sets (80% training, 20% testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a Gaussian Naive Bayes classifier
nb_classifier = GaussianNB()

# Train the classifier using the training data
nb_classifier.fit(X_train, y_train)

# Make predictions on the testing data
y_pred = nb_classifier.predict(X_test)

# Confusion matrix
res = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", res)

# Classification report
res1 = classification_report(y_test, y_pred)
print("Classification Report:\n", res1)

# Calculate the accuracy of the classifier
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
# Or optionally:
# print(f"Accuracy: {accuracy*100:.2f}%")


Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

Accuracy: 1.0


In [10]:
import numpy as np  
import pandas as pd 
from sklearn.model_selection import train_test_split  
from sklearn.naive_bayes import GaussianNB 
from sklearn.metrics import accuracy_score 
from sklearn.preprocessing import LabelEncoder 

# Load data
data = pd.read_csv('food.csv')

# Features and target
X = data.iloc[:, :3]  # first 3 columns as features
y = data.iloc[:, 3]   # 4th column as target

# Encode categorical columns
le = LabelEncoder()
categorical_columns = ['Ingredient']  # example categorical column name
for col in categorical_columns: 
    X[col] = le.fit_transform(X[col])

# Encode target variable
y = le.fit_transform(y)

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize Gaussian Naive Bayes classifier
nb_classifier = GaussianNB()

# Train the classifier
nb_classifier.fit(X_train, y_train)

# Predict on test data
y_pred = nb_classifier.predict(X_test)

# Example sample prediction
sample = [[1, 10, 9]]  # Ensure this is properly encoded if needed
prediction = nb_classifier.predict(sample)
print("Sample prediction:", prediction)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)


Sample prediction: [0]
Accuracy: 1.0
